import nodemailer from 'nodemailer';

// Generate Ethereal test credentials on the fly
let transporter: any = null;

const initializeTransporter = async () => {
  try {
    // If AWS SES credentials are provided in the environment, use them!
    if (process.env.AWS_SES_SMTP_USER && process.env.AWS_SES_SMTP_PASS) {
      console.log('[Email] Configuring AWS SES SMTP connection...');
      transporter = nodemailer.createTransport({
        host: process.env.AWS_SES_SMTP_HOST || 'email-smtp.us-east-1.amazonaws.com', // Replace with your AWS Region
        port: 587, // Standard TLS port
        secure: false, // true for 465, false for 587
        auth: {
          user: process.env.AWS_SES_SMTP_USER,
          pass: process.env.AWS_SES_SMTP_PASS,
        },
      });
      console.log('[Email] AWS SES configured successfully.');
    } else {
      // Fallback to Ethereal demo mode if no AWS keys are provided
      console.warn('[Email] No AWS SES keys found. Falling back to Ethereal Demo mode.');
      const testAccount = await nodemailer.createTestAccount();
      transporter = nodemailer.createTransport({
        host: 'smtp.ethereal.email',
        port: 587,
        secure: false,
        auth: {
          user: testAccount.user,
          pass: testAccount.pass,
        },
      });
    }
  } catch (error) {
    console.error('[Email] Failed to initialize email transporter:', error);
  }
};

initializeTransporter();

export const sendWarningEmail = async (
  toEmail: string,
  studentName: string,
  attendancePercentage: number,
  severity: string
) => {
  if (!transporter) {
    console.warn('[Email] Transporter not ready yet. Retrying...');
    return null;
  }

  const subject = `[URGENT] ${severity.toUpperCase()} Attendance Warning - ${studentName}`;
  const text = `Dear Parent/Student,

This is an automated system alert from CampusGuard.

The overall attendance for ${studentName} has dropped to ${attendancePercentage}%.
This is a ${severity} risk warning. Immediate action is required to avoid academic penalties.

Please contact the department head immediately.

Sincerely,
CampusGuard Administration`;

  const html = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 8px; overflow: hidden;">
      <div style="background-color: ${severity === 'high' ? '#dc2626' : '#ea580c'}; padding: 20px; color: white;">
        <h2 style="margin: 0;">CampusGuard Urgent Alert</h2>
      </div>
      <div style="padding: 20px;">
        <p>Dear Parent/Student,</p>
        <p>This is an automated system alert regarding <strong>${studentName}</strong>.</p>
        <div style="background-color: #f8fafc; padding: 15px; border-left: 4px solid ${severity === 'high' ? '#dc2626' : '#ea580c'}; margin: 20px 0;">
          <p style="margin: 0; font-size: 16px;">Current Attendance: <strong style="color: ${severity === 'high' ? '#dc2626' : '#ea580c'}; font-size: 20px;">${attendancePercentage}%</strong></p>
        </div>
        <p>This is a <strong>${severity.toUpperCase()}</strong> risk warning. Immediate action is required to avoid academic penalties or suspension.</p>
        <p>Please contact the department head immediately to schedule a meeting and submit any relevant medical documents.</p>
        <hr style="border: 0; border-top: 1px solid #e2e8f0; margin: 20px 0;" />
        <p style="color: #64748b; font-size: 12px; margin: 0;">This is an automated message generated by the CampusGuard Attendance System. Do not reply to this email.</p>
      </div>
    </div>
  `;

  try {
    const info = await transporter.sendMail({
      from: '"CampusGuard Admin" <admin@campusguard.edu>',
      to: toEmail,
      subject: subject,
      text: text,
      html: html,
    });

    console.log(`[Email] Message sent successfully to ${toEmail}`);
    // Ethereal specific - provides a URL to view the sent email in the browser!
    const previewUrl = nodemailer.getTestMessageUrl(info);
    console.log(`[Email] Preview URL: ${previewUrl}`);
    
    return previewUrl;
  } catch (error) {
    console.error(`[Email] Error sending email to ${toEmail}:`, error);
    return null;
  }
};
